clean:
	./gradlew clean

build:
	./gradlew build

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

sonar:
	./gradlew sonar

lint:
	./gradlew checkstyleMain

run:
	./gradlew run --args="\"src/test/resources/filepath1.json\" \"src/test/resources/filepath2.json\""

.PHONY: build
